version: '3.8'

services:
  dev:
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - '5000:5000'
      - '9229:9229'
    networks:
      - nesjs-network
    env_file:
      - .development.env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mysqldb
    restart: unless-stopped
  prod:
    container_name: nestjs_api_prod
    image: nestjs-api-prod:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - '5000:5000'
      - '9229:9229'
    networks:
      - nesjs-network
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
  mysqldb:
    image: mysql:5.7
    restart: always
    env_file:
      - .development.env
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

networks:
  nesjs-network:
volumes:
  my-db: