version: '3.8'

services:
  app:
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    build:
      context: .
    command: npm run start:prod
    ports:
      - '5000:5000'
      - '9229:9229'
    networks:
      - nesjs-network
    env_file:
      - .development.env
    volumes:
      - .:/app
      - /app/node_modules
#    depends_on:
#      - mysqldb
    restart: unless-stopped

networks:
  nesjs-network:
