version: '3.8'

services:
  dev-db:
    container_name: postgres
    image: postgres:12
    env_file:
      - .development.env
    networks:
      - nesjs-network
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
  dev:
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - '4000:4000'
      - '9229:9229'
    networks:
      - nesjs-network
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - dev-db
    restart: unless-stopped
  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - .production.env
    networks:
      - nesjs-network
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  prod:
    container_name: nestjs_api_prod
    image: nestjs-api-prod:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - '5000:5000'
      - '9229:9229'
    networks:
      - nesjs-network
    env_file:
      - .production.env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  pgdata:
networks:
  nesjs-network: